# Generated by Django 5.2.7 on 2025-10-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_alter_programador_apellido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTarea', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=100)),
                ('estimacion', models.IntegerField(blank=True, null=True)),
                ('asignada', models.BooleanField(default=False)),
            ],
        ),
    ]
